/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test3 */

#ifndef _Included_Test3
#define _Included_Test3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test3
 * Method:    foo
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_Test3_foo___3Ljava_lang_String_2I
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     Test3
 * Method:    foo
 * Signature: ([Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_Test3_foo___3Ljava_lang_String_2F
  (JNIEnv *, jobject, jobjectArray, jfloat);

/*
 * Class:     Test3
 * Method:    bar_03148_0314a_03145_03186
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test3_bar_03148_0314a_03145_03186
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
